### ISSUE TITLE
Find out if lesson is exam

### ISSUE THREAD

**Issue by littlegamer757** [TheNoim/WebUntis#23]
I was wondering if I somehow can find out if there is an exam in a specific lesson, for example gotten from a timetable. I could get all of the information about a lesson except for the red marked ones.
![image](https://user-images.githubusercontent.com/46902503/71326848-c2675100-2500-11ea-9eb4-058103856e80.png)

**Comment by TheNoim** [comment]
It is possible. However, because our school didn't use the exam features in webuntis I was never able to test it. Therefore, I never implemented it.

**Comment by littlegamer757** [comment]
That means I cannot find out if there is an exam in a lesson with this API/Wrapper?

**Comment by TheNoim** [comment]
Currently, no. You could make a pull request to actually implement it. However, I can not test it.

**Comment by littlegamer757** [comment]
I think I'm not capable of doing that, but thank you anyway!
