### ISSUE TITLE
Just a few questions

### ISSUE THREAD

**Issue by luwol03** [TheNoim/WebUntis#29]
Hello,

I have got the api docs with a email to helpdesk. And now I have a few questions.

1. What version of the documentation you're using? And how much pages you have? (Mine is from 20.09.2018 and has 19 pages)

2. In mine there is nothing about getting homeworks and a few other stuff. Only json rpc and nothing about a rest API. Did you figured out the rest api yourself?

3. The guy from the untis team, who send me the documentation said:
> The query interval of your program must NOT be less than 60 minutes. Otherwise the query will be blocked by the system.

Have you any experience with testing your program? Did you got blocked?

4. And in my sheet I can't find anything about the secret authentication and anonymous login. Did you figured out this also yourself?

Best regards.

**Comment by TheNoim** [comment]
Hi,

> 1. What version of the documentation you're using? And how much pages you have? (Mine is from 20.09.2018 and has 19 pages)

I have the same version. 

> 2. In mine there is nothing about getting homeworks and a few other stuff. Only json rpc and nothing about a rest API. Did you figured out the rest api yourself?

Figured it out by myself.

> 3. The guy from the untis team, who send me the documentation said:
> 
> The query interval of your program must NOT be less than 60 minutes. Otherwise the query will be blocked by the system.
Have you any experience with testing your program? Did you got blocked?

I think they don't have a blocking system which triggers that early. Never got blocked. Just don't abuse it and you should be fine. If there servers can not handle 2 request every hour, then they probably did something wrong while developing WebUntis. 

> 4. And in my sheet I can't find anything about the secret authentication and anonymous login. Did you figured out this also yourself?

Yes, again. I figured it out by myself. Nothing there in the official documentation.

**Comment by luwol03** [comment]
Ok, thank you very much for awnsering. I like your api wrapper.

**Comment by luwol03** [comment]
Do you know, if there is also something to get all teacher who theaches me in which lesson?

**Comment by TheNoim** [comment]
https://github.com/TheNoim/WebUntis/blob/master/index.d.ts#L49

**Comment by luwol03** [comment]
That's funny, could it be that my school blocks fetching also the teacher? This is one lesson json object Im getting.
```json
{
  "id": 357397,
  "date": 20200922,
  "startTime": 955,
  "endTime": 1040,
  "kl": [
    {
      "id": 280,
      "name": "11",
      "longname": " (314)"
    },
    {
      "id": 285,
      "name": "11",
      "longname": "(320)"
    }
  ],
  "su": [
    {
      "id": 1,
      "name": "KR",
      "longname": "Kath. Relogion"
    }
  ],
  "ro": [
    {
      "id": 44,
      "name": "314",
      "longname": "(9d)"
    }
  ],
  "lsnumber": 9800,
  "activityType": "Unterricht"
}
```

**Comment by TheNoim** [comment]
> That's funny, could it be that my school blocks fetching also the teacher? This is one lesson json object Im getting.

It could be. Can you make a screenshot of some lessons on the webuntis page?

**Comment by luwol03** [comment]
![image](https://user-images.githubusercontent.com/60048565/94143270-e250ea00-fe6f-11ea-921d-e2e7a8393bd5.png)
It's funny, because on the web untis page I can see my teachers, but on the mobile app i can't. Could it be that webuntis fetch the data an other way like the mobile app? And the mobile app use the offfical api?

**Comment by TheNoim** [comment]
Currently, there are three known apis to me:
1. The official
2. WebAPI (Used by the webpage)
3. App API 

However, this is the first time that I encountered that some api is missing some data. I mean, if some api is returning the data, we should be able to get it somehow. But we need to modify the api client.

**Comment by luwol03** [comment]
how do you recommend the login management? just login for one api call and then log out or leave the session valid and not logout and validate the session before every api call?

**Comment by TheNoim** [comment]
> how do you recommend the login management? just login for one api call and then log out or leave the session valid and not logout and validate the session before every api call?

If you really know you only do one request, you can logout. However, a session is only valid for 15 minutes. So, if you do more than one request in 15 minutes, you can just leave it. The client will refresh the session by itself.
