### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by TheNoim** [TheNoim/WebUntis#32]
Currently, there are no tests for the package. 

We should at least add some basic tests.

**Comment by eavam** [comment]
Can I work on it? 🙂

**Comment by TheNoim** [comment]
Do you have an account to test? Sadly, Untis stopped the Demo instance.

**Comment by eavam** [comment]
Nope, sorry. I was thinking about unit tests on mocks. Not a real request. 😕

**Comment by TheNoim** [comment]
Mocking would also be ok. You can go ahead if you want. Should I assign you?

**Comment by eavam** [comment]
I think, yes.

**Comment by eavam** [comment]
I have done #34.
Sorry about size PR 😐
